package org.example.rentoza.payment;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Immutable-by-intent ledger record for every payment operation.
 *
 * <p>One row per provider call. Provides:
 * <ul>
 *   <li>Full audit trail of all payment operations</li>
 *   <li>Idempotency tracking — callers look up by {@code idempotencyKey} before calling provider</li>
 *   <li>Base for financial reconciliation against provider statements</li>
 *   <li>Source of truth for payout calculations</li>
 * </ul>
 *
 * <h2>Relationship to Booking</h2>
 * <p>A booking may have multiple transactions:
 * <ul>
 *   <li>AUTHORIZE — booking payment hold at creation</li>
 *   <li>CAPTURE — booking payment capture at pickup</li>
 *   <li>AUTHORIZE — security deposit hold at check-in</li>
 *   <li>RELEASE or CAPTURE — deposit settled at checkout</li>
 *   <li>REFUND — one or more refunds on cancellation</li>
 * </ul>
 */
@Entity
@Table(
    name = "payment_transactions",
    indexes = {
        @Index(name = "idx_pt_booking_id",       columnList = "booking_id"),
        @Index(name = "idx_pt_idempotency_key",  columnList = "idempotency_key", unique = true),
        @Index(name = "idx_pt_provider_ref",     columnList = "provider_reference"),
        @Index(name = "idx_pt_status",           columnList = "status"),
        @Index(name = "idx_pt_created_at",       columnList = "created_at")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Version
    private Long version;

    // ── Booking reference ─────────────────────────────────────────────────────

    @Column(name = "booking_id", nullable = false)
    private Long bookingId;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    // ── Operation metadata ────────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "operation", nullable = false, length = 30)
    private PaymentOperation operation;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private PaymentTransactionStatus status;

    /**
     * Deterministic idempotency key — generated by {@link PaymentIdempotencyKey}.
     * Unique constraint prevents duplicate transactions even on retry storms.
     */
    @Column(name = "idempotency_key", nullable = false, length = 64, unique = true)
    private String idempotencyKey;

    // ── Financial ─────────────────────────────────────────────────────────────

    @Column(name = "amount", precision = 19, scale = 2)
    private BigDecimal amount;

    @Column(name = "currency", length = 10)
    @Builder.Default
    private String currency = "RSD";

    // ── Provider references ───────────────────────────────────────────────────

    /** Provider-assigned reference for this transaction (auth ID, txn ID, refund ID). */
    @Column(name = "provider_reference", length = 100)
    private String providerReference;

    /** Provider-assigned authorization reference (set on AUTHORIZE, preserved through CAPTURE). */
    @Column(name = "provider_auth_id", length = 100)
    private String providerAuthId;

    /** Raw provider status string for debugging. */
    @Column(name = "raw_provider_status", length = 100)
    private String rawProviderStatus;

    /** Redirect URL for 3DS2 flows (only set when outcome is REDIRECT_REQUIRED). */
    @Column(name = "redirect_url", length = 500)
    private String redirectUrl;

    /** 3DS2 session token (correlates redirect return). */
    @Column(name = "session_token", length = 200)
    private String sessionToken;

    // ── Failure tracking ──────────────────────────────────────────────────────

    @Column(name = "error_code", length = 50)
    private String errorCode;

    @Column(name = "error_message", length = 500)
    private String errorMessage;

    @Column(name = "attempt_count", nullable = false)
    @Builder.Default
    private int attemptCount = 1;

    @Column(name = "max_attempts", nullable = false)
    @Builder.Default
    private int maxAttempts = 3;

    @Column(name = "next_retry_at")
    private Instant nextRetryAt;

    // ── Timestamps ────────────────────────────────────────────────────────────

    @Column(name = "provider_expiry")
    private Instant providerExpiry;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;

    @Column(name = "completed_at")
    private Instant completedAt;

    // ── Helpers ───────────────────────────────────────────────────────────────

    public boolean isTerminal() {
        return status == PaymentTransactionStatus.SUCCEEDED
                || status == PaymentTransactionStatus.FAILED_TERMINAL
                || status == PaymentTransactionStatus.MANUAL_REVIEW;
    }

    public boolean isRetryEligible() {
        return (status == PaymentTransactionStatus.FAILED_RETRYABLE
                || status == PaymentTransactionStatus.PROCESSING)
                && attemptCount < maxAttempts;
    }

    // ── Enums ─────────────────────────────────────────────────────────────────

    public enum PaymentOperation {
        AUTHORIZE,
        CAPTURE,
        CHARGE,
        REFUND,
        RELEASE,
        PAYOUT
    }

    public enum PaymentTransactionStatus {
        /** Provider call in flight. */
        PROCESSING,
        /** Provider confirmed success. */
        SUCCEEDED,
        /** Redirect required — awaiting guest 3DS2 completion. */
        REDIRECT_REQUIRED,
        /** Provider async confirmation pending. */
        PENDING_CONFIRMATION,
        /** Transient failure — will be retried. */
        FAILED_RETRYABLE,
        /** Hard decline — do not retry. */
        FAILED_TERMINAL,
        /** Max retries exceeded — operator action required. */
        MANUAL_REVIEW
    }
}
