spring.application.name=Rentoza
spring.datasource.url=jdbc:mysql://localhost:3306/rentoza?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Kljaja01
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=warn
spring.jpa.open-in-view=false
jwt.secret=YmVzdHNlY3JldGtleTEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=
jwt.expiration=86400000