package org.example.rentoza.security.supabase;

import io.jsonwebtoken.*;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.security.Key;
import java.util.Date;
import java.util.UUID;
import java.util.function.Function;

/**
 * Supabase JWT validation utility.
 * 
 * <p>Validates JWT tokens issued by Supabase Auth (HS256 algorithm).
 * Unlike the old JwtUtil which generated tokens, this class only validates
 * tokens generated by Supabase Auth.
 * 
 * <p>Token Structure (Supabase JWT):
 * <ul>
 *   <li>sub: Supabase Auth UUID (user identifier)</li>
 *   <li>aud: "authenticated" for logged-in users</li>
 *   <li>role: "authenticated" or "anon"</li>
 *   <li>email: User's email address</li>
 *   <li>exp: Expiration timestamp</li>
 *   <li>iat: Issued-at timestamp</li>
 * </ul>
 * 
 * @since Phase 2 - Supabase Auth Migration
 */
@Component
public class SupabaseJwtUtil {

    private static final Logger log = LoggerFactory.getLogger(SupabaseJwtUtil.class);

    private final Key key;
    private final String supabaseUrl;

    public SupabaseJwtUtil(
            @Value("${supabase.jwt-secret}") String jwtSecret,
            @Value("${supabase.url}") String supabaseUrl
    ) {
        // Supabase JWT secret is Base64 encoded
        this.key = Keys.hmacShaKeyFor(Decoders.BASE64.decode(jwtSecret));
        this.supabaseUrl = supabaseUrl;
        log.info("SupabaseJwtUtil initialized for project: {}", supabaseUrl);
    }

    // =====================================================
    // 🔐 TOKEN VALIDATION
    // =====================================================

    /**
     * Validate a Supabase JWT token.
     * 
     * @param token JWT token string (without "Bearer " prefix)
     * @return true if token is valid and not expired
     */
    public boolean validateToken(String token) {
        try {
            Jwts.parserBuilder()
                    .setSigningKey(key)
                    .build()
                    .parseClaimsJws(token);
            return true;
        } catch (ExpiredJwtException e) {
            log.debug("Supabase JWT expired: {}", e.getMessage());
            return false;
        } catch (UnsupportedJwtException | MalformedJwtException e) {
            log.warn("Invalid Supabase JWT: {}", e.getClass().getSimpleName());
            return false;
        } catch (io.jsonwebtoken.security.SignatureException e) {
            log.warn("Supabase JWT signature validation failed");
            return false;
        } catch (IllegalArgumentException e) {
            log.debug("Empty or null JWT token");
            return false;
        }
    }

    // =====================================================
    // 🧾 CLAIMS EXTRACTION
    // =====================================================

    /**
     * Extract the Supabase user UUID from the token.
     * This is the primary user identifier in Supabase Auth.
     * 
     * @param token JWT token string
     * @return Supabase Auth user UUID
     */
    public UUID getSupabaseUserId(String token) {
        String sub = extractClaim(token, Claims::getSubject);
        return sub != null ? UUID.fromString(sub) : null;
    }

    /**
     * Extract the user's email from the token.
     * 
     * @param token JWT token string
     * @return User's email address
     */
    public String getEmailFromToken(String token) {
        return extractClaim(token, claims -> claims.get("email", String.class));
    }

    /**
     * Extract the Supabase role from the token.
     * Typically "authenticated" for logged-in users, "anon" for anonymous.
     * 
     * @param token JWT token string
     * @return Supabase role string
     */
    public String getSupabaseRole(String token) {
        return extractClaim(token, claims -> claims.get("role", String.class));
    }

    /**
     * Check if the token belongs to an authenticated user (not anonymous).
     * 
     * @param token JWT token string
     * @return true if user is authenticated
     */
    public boolean isAuthenticated(String token) {
        String role = getSupabaseRole(token);
        return "authenticated".equals(role);
    }

    /**
     * Extract the token expiration date.
     * 
     * @param token JWT token string
     * @return Expiration date
     */
    public Date getExpirationDateFromToken(String token) {
        return extractClaim(token, Claims::getExpiration);
    }

    /**
     * Extract all claims from the token.
     * 
     * @param token JWT token string
     * @return All JWT claims
     */
    public Claims getAllClaims(String token) {
        return extractAllClaims(token);
    }

    /**
     * Extract a specific claim using a resolver function.
     * 
     * @param token JWT token string
     * @param claimsResolver Function to extract the desired claim
     * @return The extracted claim value
     */
    public <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = extractAllClaims(token);
        return claimsResolver.apply(claims);
    }

    private Claims extractAllClaims(String token) {
        try {
            return Jwts.parserBuilder()
                    .setSigningKey(key)
                    .build()
                    .parseClaimsJws(token)
                    .getBody();
        } catch (ExpiredJwtException e) {
            // For expired tokens, we can still extract claims
            return e.getClaims();
        } catch (JwtException | IllegalArgumentException e) {
            throw new RuntimeException("Unable to parse Supabase JWT: " + e.getMessage());
        }
    }

    // =====================================================
    // 🔧 UTILITY METHODS
    // =====================================================

    /**
     * Check if a token is expired.
     * 
     * @param token JWT token string
     * @return true if token is expired
     */
    public boolean isTokenExpired(String token) {
        try {
            Date expiration = getExpirationDateFromToken(token);
            return expiration != null && expiration.before(new Date());
        } catch (Exception e) {
            return true; // Treat errors as expired
        }
    }

    /**
     * Get the Supabase project URL.
     * Used for constructing API calls to Supabase.
     * 
     * @return Supabase project URL
     */
    public String getSupabaseUrl() {
        return supabaseUrl;
    }
}
