package org.example.rentoza.booking.dto;

import jakarta.validation.constraints.AssertTrue;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

import org.example.rentoza.booking.util.TripDurationCalculator;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

/**
 * DTO for creating a new booking request.
 * 
 * <h2>Exact Timestamp Architecture</h2>
 * Uses precise start/end timestamps instead of date + time window.
 * 
 * <h2>Timezone</h2>
 * All times are interpreted as Europe/Belgrade local time.
 * Frontend should send ISO-8601 format without offset: "2025-10-10T10:00:00"
 * 
 * <h2>Time Granularity</h2>
 * Times should be on 30-minute boundaries (e.g., 09:00, 09:30, 10:00).
 * 
 * <h2>Minimum Duration</h2>
 * Booking must be at least 24 hours (overnight rental required).
 */
@Getter
@Setter
public class BookingRequestDTO {
    
    @NotNull(message = "Car ID is required")
    private Long carId;

    /**
     * Exact trip start timestamp.
     * Format: ISO-8601 LocalDateTime (e.g., "2025-10-10T10:00:00")
     * Timezone: Interpreted as Europe/Belgrade
     */
    @NotNull(message = "Start time is required")
    @FutureOrPresent(message = "Start time must be now or in the future")
    private LocalDateTime startTime;

    /**
     * Exact trip end timestamp.
     * Format: ISO-8601 LocalDateTime (e.g., "2025-10-12T10:00:00")
     * Timezone: Interpreted as Europe/Belgrade
     */
    @NotNull(message = "End time is required")
    @Future(message = "End time must be in the future")
    private LocalDateTime endTime;

    private String insuranceType = "BASIC"; // BASIC, STANDARD, PREMIUM
    private boolean prepaidRefuel = false;

    /**
     * Payment method identifier (token from frontend payment form).
     * Required for payment authorization at booking time.
     * 
     * <p>For mock payment provider: use "mock_default" or any non-empty string.
     * <p>For real providers (Stripe/Mori): this will be the tokenized payment method ID.
     * 
     * <p><b>P1 Fix:</b> Now required — must be explicitly provided by the frontend.
     * No longer defaults to "mock_default".
     */
    @jakarta.validation.constraints.NotBlank(message = "Payment method is required")
    @Size(max = 255, message = "Payment method ID must not exceed 255 characters")
    private String paymentMethodId;

    /**
     * Client-generated idempotency key to prevent duplicate booking creation on retry.
     * 
     * <p><b>P1 Fix:</b> Without this, a network retry could create duplicate bookings
     * and duplicate payment authorizations. The key is stored on the Booking entity
     * with a unique constraint.
     * 
     * <p>Format: UUID v4 generated by the frontend before first submission attempt.
     * Re-used on retries so the server can detect duplicates.
     */
    @Size(max = 64, message = "Idempotency key must not exceed 64 characters")
    private String idempotencyKey;

    // ========================================================================
    // GEOSPATIAL LOCATION FIELDS (Phase 2.4 - Pickup Location Snapshot)
    // ========================================================================
    // These fields capture the agreed pickup location at booking time.
    // The location is immutable after booking creation to prevent hosts
    // from moving the car without guest consent.
    //
    // If pickupLatitude and pickupLongitude are null, the car's home location
    // is used as the default pickup point.

    /**
     * Pickup location latitude (WGS84).
     * Must be within Serbia bounds: 42.2°N to 46.2°N
     */
    @DecimalMin(value = "42.2", message = "Latitude must be within Serbia bounds (minimum 42.2°N)")
    @DecimalMax(value = "46.2", message = "Latitude must be within Serbia bounds (maximum 46.2°N)")
    private BigDecimal pickupLatitude;

    /**
     * Pickup location longitude (WGS84).
     * Must be within Serbia bounds: 18.8°E to 23.0°E
     */
    @DecimalMin(value = "18.8", message = "Longitude must be within Serbia bounds (minimum 18.8°E)")
    @DecimalMax(value = "23.0", message = "Longitude must be within Serbia bounds (maximum 23.0°E)")
    private BigDecimal pickupLongitude;

    /**
     * Human-readable pickup address (reverse-geocoded or user-provided).
     * Example: "Terazije 26, Beograd"
     */
    @Size(max = 255, message = "Pickup address must not exceed 255 characters")
    private String pickupAddress;

    /**
     * City name for UI grouping and search.
     * Example: "Belgrade", "Novi Sad", "Niš"
     */
    @Size(max = 50, message = "City must not exceed 50 characters")
    private String pickupCity;

    /**
     * Postal code (optional).
     * Example: "11000"
     */
    @Size(max = 10, message = "Zip code must not exceed 10 characters")
    private String pickupZipCode;

    /**
     * Whether guest requests delivery to a custom location.
     * If true and pickupLatitude/pickupLongitude are provided,
     * a delivery fee will be calculated.
     */
    private boolean deliveryRequested = false;

    /**
     * Validates that end time is after start time.
     */
    @AssertTrue(message = "End time must be after start time")
    private boolean isEndTimeAfterStartTime() {
        if (startTime == null || endTime == null) {
            return true; // Let @NotNull handle nulls
        }
        return endTime.isAfter(startTime);
    }

    /**
     * Validates minimum rental duration (24 hours).
     */
    @AssertTrue(message = "Minimum rental duration is 24 hours")
    private boolean isMinimumDurationMet() {
        if (startTime == null || endTime == null) {
            return true; // Let @NotNull handle nulls
        }
        long hours = ChronoUnit.HOURS.between(startTime, endTime);
        return hours >= 24;
    }

    /**
     * Validates that times are on 30-minute boundaries.
     */
    @AssertTrue(message = "Times must be on 30-minute boundaries (e.g., 09:00, 09:30)")
    private boolean isTimeGranularityValid() {
        if (startTime == null || endTime == null) {
            return true; // Let @NotNull handle nulls
        }
        boolean startValid = startTime.getMinute() == 0 || startTime.getMinute() == 30;
        boolean endValid = endTime.getMinute() == 0 || endTime.getMinute() == 30;
        return startValid && endValid;
    }

    /**
     * Validates that if delivery is requested, pickup coordinates are provided.
     */
    @AssertTrue(message = "Pickup coordinates are required when delivery is requested")
    private boolean isDeliveryCoordinatesValid() {
        if (!deliveryRequested) {
            return true; // No delivery = no coordinate requirement
        }
        return pickupLatitude != null && pickupLongitude != null;
    }

    /**
     * Validates that both latitude and longitude are provided together (or neither).
     */
    @AssertTrue(message = "Both latitude and longitude must be provided together")
    private boolean isCoordinatesPairValid() {
        boolean hasLat = pickupLatitude != null;
        boolean hasLon = pickupLongitude != null;
        return hasLat == hasLon; // Both present or both absent
    }

    /**
     * Validates that the start time is a valid local time (not in a DST gap).
     * 
     * <p>During spring forward (March ~29 in Serbia), times like 02:30 don't exist
     * because clocks jump from 01:59:59 directly to 03:00:00.
     * 
     * @since Phase 3 - Enterprise Hardening
     */
    @AssertTrue(message = "Nevalidan datum/vreme - vreme ne postoji zbog promene letnjeg računanja vremena")
    private boolean isStartTimeValidForDst() {
        if (startTime == null) {
            return true; // Let @NotNull handle nulls
        }
        return TripDurationCalculator.isValidLocalTime(startTime);
    }

    /**
     * Validates that the end time is a valid local time (not in a DST gap).
     * 
     * @since Phase 3 - Enterprise Hardening
     */
    @AssertTrue(message = "Nevalidan datum/vreme završetka - vreme ne postoji zbog promene letnjeg računanja vremena")
    private boolean isEndTimeValidForDst() {
        if (endTime == null) {
            return true; // Let @NotNull handle nulls
        }
        return TripDurationCalculator.isValidLocalTime(endTime);
    }

    /**
     * Warns (via log) if the booking spans a DST transition.
     * Does not reject - just returns true but can be used for monitoring.
     * 
     * @since Phase 3 - Enterprise Hardening
     */
    public boolean spansDstTransition() {
        if (startTime == null || endTime == null) {
            return false;
        }
        return TripDurationCalculator.spansDstTransition(startTime, endTime);
    }

    // ========== CONVENIENCE METHODS ==========

    /**
     * Calculate the duration in hours.
     */
    public long getDurationHours() {
        if (startTime == null || endTime == null) {
            return 0;
        }
        return ChronoUnit.HOURS.between(startTime, endTime);
    }

    /**
     * Calculate the duration in 24-hour periods (for pricing).
     * Rounds up to the nearest full day.
     */
    public int getDurationDays() {
        long hours = getDurationHours();
        return Math.max(1, (int) Math.ceil(hours / 24.0));
    }

    /**
     * Check if a custom pickup location is provided.
     */
    public boolean hasCustomPickupLocation() {
        return pickupLatitude != null && pickupLongitude != null;
    }
}
